# Site wide configuration

title:            this is a blog
locale:           en_GB
#url:              http://goochjs.github.io
#url:              http://localhost:4000
url:              http://www.goochgooch.co.uk

# Jekyll configuration

#permalink:   /:categories/:title/
permalink:   /:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Jeremy Gooch
  avatar: j_guitar_edited.jpg
  bio: "Guitarist and IT architect"
  email: 
  twitter: goochjs
  facebook: goochjs
  linkedin: jeremygooch
  youtube: goochjs
  google:
    plus: JeremyGooch
    analytics: UA-60678522-1
    verify: 
    ad-client: 
    ad-slot: 
  instagram: goochjs
  lastfm: goochjs
  soundcloud: goochjs
  bing-verify: 
  github: goochjs
  stackoverflow: 1829190/jeremy-gooch
  xing: #username
  disqus-shortname: goochgooch
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
